s3_file_field/fields.py
Previously, this was calling the superclass method with "form_class=None".
=> When in UNSUPPORTED mode, make S3FileField.formfield a no-op

s3_file_field/forms.py, s3_file_field/widgets.py
Ultimately, any dynamic `Storage` detection should be based on the particular `Storage` used by an `S3FieldField` instance, not Django's global media `Storage`.
`form.FileField` and `Widget` instances do not have a reference to the `S3FieldFild` which they support, so they should never attempt to detect the current `Storage` or alter their behavior accordingly. Instead, the use of a `form.FileField` vs. `S3FormFileField` should be determined exclusively by `S3FileField.formfield` or by direct instantiation from downstream projects.
Future work will attempt to make `S3FileField.formfield` detect the current `Storage`.
=> Remove dynamic Storage detection from form.FileField and Widget classes

s3_file_field/checks.py, s3_file_field/constants.py, s3_file_field/fields.py
* Allow `_get_storage_provider` to check against non-media Storages too
* Add a `constants.supported_storage` utility function
* Use the `S3FileField`'s own storage instance, rather than the media storage
=> Improve supported storage detection

client/package-lock.json, client/package.json, client/src/S3FileInput.ts, client/src/client.ts
Adds `client.ts`, which for now is just a drop-in replacement for `uploader.ts` that does multipart upload instead of using the AWS client. The method signatures and exports are the same, although some arguments are now ignored. 
For posterity, the invocation to update `joist.js` is to run `python setup.py jsdeps`.
=> Multipart client

client/src/client.ts, s3_file_field/forms.py, s3_file_field/views.py
When adding the multipart client I set the `value` on the `<input>` element in the form to `''` as a placeholder, as I didn't think it was significant. That value is passed in to the S3FakeFile and will fail validation if it isn't correctly formatted.
That value also involves a signature that is not calculated in multipart uploads, so I removed that S3FakeFile validation step.
Submitting the test/functional form works correctly now.
=> Add valid value to uploaded S3FileInput

README.md, s3_file_field/views.py
Using `generate_filename`/`upload_to` seems like the correct answer, but I really don't like having to ignore the `instance` argument. It's assumed that `generate_filename` is being used to create a new model during a form submission, but during upload we don't have a model instance we can pass. Using `None` is hacky, but seems less hacky to me than reimplementing `generate_filename`.
=> Use upload_to instead of hardcoded UUID prefix

client/src/style.scss
Fixes #106
Safari was rendering the component strangely because of an unnecessary `flex-column` class. After removal the admin widget renders the same for me in Safari and in Chrome.
=> Remove unnecessary flex from admin widget

s3_file_field/fields.py, tests/test_forms.py
This should result in the model having a normal, sane `FieldFile` (wrapping an ordinary `File` subclass) after saving.
Fixes #105.
=> Coerce FieldFile content out of an S3FakeFile before saving

s3_file_field/fields.py, s3_file_field/forms.py, s3_file_field/widgets.py, tests/test_forms.py
The reworks the parsing and validation pipeline to be more compatible with the way that Django's form `Field.clean` works. S3FF now properly handles empty form submissions (and has basic tests for this) without raising a 500. It also theoretically supports the usage of the "clear" checkbox for fields where `blank=True`, but further testing should be added in a subsequent PR.
=> Allow form fields to handle empty and cleared uploads

client/package-lock.json, client/package.json, django-s3-file-field-client/package-lock.json
node-sass is deprecated and harder to run cross-platform.
=> Switch node-sass to sass

django-s3-file-field-client/src/client.ts, s3_file_field/_multipart.py, s3_file_field/_multipart_boto3.py, s3_file_field/_multipart_minio.py, s3_file_field/urls.py, s3_file_field/views.py, s3_file_field/widgets.py, tests/test_multipart.py, tests/test_serializers.py, tests/test_views.py
Finalize requests are now presigned, so now clients must call the provided URL with the provided request body to finalize the object creation.
=> Presign finalize

s3_file_field/_multipart.py
This was not actually used in any calls.
=> Remove the optional part_size parameter from part_size

.github/workflows/pythonpackage.yml, DEVELOPMENT.md, setup.py
All other Girder 4 tools require Python 3.8.
=> Require Python 3.8

example/s3ff_example/settings.py, s3_file_field/views.py
When `SessionAuthentication` is included as an authentication option, it
requires a CSRF token on all requests, which is not included by the JS
client. Now the upload views explicitly do not use any authentication so
`SessionAuthentication` is never applied.
Fixes #112
=> Upload views explicitly do not use authentication

django-s3-file-field-client/src/client.ts, widget/src/S3FileInput.ts
This adds progress reporting support on top of #161 
The API for progress events I'm proposing here is extremely explicit. It makes no attempt to fake progress during init and finalize, rather pushing that responsibility out to downstreams if they desire that behavior. Other clients (like the one I'm writing) can instead opt to show indeterminate progress, or even a helpful message about what's going on during the init and finalization periods.
=> Add progress callback to TS client

s3_file_field/forms.py, widget/src/S3FileInput.ts, widget/src/style.scss
Auto-upload was always enabled, so the non-auto-upload capability was never used and added to the code maintenance burden.
=> Remove non-auto-upload capability from widget

widget/package.json
These don't work, so it's wasted space to publish them.
=> Disable widget sourcemaps

s3_file_field/fields.py, s3_file_field/forms.py, s3_file_field/widgets.py
This was part of an earlier different architecture, and is no longer useful for debugging.
=> Remove inoperative code from the server app

s3_file_field/views.py
When doing CSRF enforcement for `SessionAuthentication`, DRF does not look at the destination view for exemptions.
=> Remove pointless csrf_exempt decorators

s3_file_field/testing.py, tests/test_test_client.py
Fixes #226 
This largely replicates the behavior/structure of the existing [python client](https://github.com/girder/django-s3-file-field/blob/master/python-client/s3_file_field_client/__init__.py), but replaces actual requests with requests to a DRF test `APIClient`.
I realize some things between the python client and this module are duplicated (namely the `_File` class), but I didn't want to make assumptions / complicate the codebase just to abstract away that one thing. If this is an issue and there's a better way to approach it please lmk.
I've also modified the behavior of the `upload_file` function to directly return the `field_value`, instead of a dict with the format:
```python
{
'field_value': field_value,
}
```
It seems to me it's more useful to just return the direct …
=> Add python test client

python-client/s3_file_field_client/__init__.py, s3_file_field/testing.py, tests/test_test_client.py
This matches the behavior of the JS client and the design intent.
Found by @jbeezley in #228.
=> Fix the return value of S3FileFieldClient.upload_file

setup.py, tox.ini
Django 4.0 is EOL: https://www.djangoproject.com/download/#supported-versions
=> Remove support for Django 4.0

example/docker-compose.yml
This is not well-integrated with the rest of the example app.
=> Simplify Docker Compose config, removing port customization option

tests/test_registry.py
This was caused by a change in pytest 8:
> [#9288](https://github.com/pytest-dev/pytest/issues/9288): [warns()](https://docs.pytest.org/en/latest/reference/reference.html#pytest.warns) now re-emits unmatched warnings when the context closes – previously it would consume all warnings, hiding those that were not matched by the function.
> 
> While this is a new feature, we announce it as a breaking change because many test suites are configured to error-out on warnings, and will therefore fail on the newly-re-emitted warnings.
=> Fix a test failure due to Django warnings
