- .gitignore
- README.md
- django/requirements.txt
- vue/src/components/JoistUpload.vue
add setup notes + use `psycopg2-binary` to use prebuilt library
> improve setup

- django/core/models.py
- django/core/views.py
- django/joist/admin.py
- django/joist/migrations/0001_add_blob_model.py
- django/joist/models.py
- django/joist/serializers.py
- django/joist/settings.py
- django/joist/urls.py
- django/joist/views.py
- vue/src/components/JoistUpload.vue
based on #7 
better split of app (joist) and core (field,...) + client side restructure
> restructuring

- README.md
- client/package.json
- client/webpack.config.js
- client/webpack.config.widget.js
- setup.cfg
- setup.py
> prepare for release

- s3_file_field/urls.py
- s3_file_field/widgets.py
I don't know how these were missed, I made these changes in my last PR.
> Fix bad imports which broke everything

- example/tests/fuzzy.py
- example/tests/test_multipart_upload.py
- s3_file_field/views.py
> Require content length as a parameter in multipart upload

- s3_file_field/_registry.py
- s3_file_field/fields.py
- tests/conftest.py
- tests/test_registry.py
- tox.ini
Also, add unit testing support.
> Add a registry of used S3FileField instances

- client/src/S3FileInput.ts
- client/src/client.ts
- s3_file_field/views.py
- tests/functional/tests/test_multipart_upload.py
- tests/unit/test_serializers.py
> Upload to field storage

- tests/conftest.py
- tests/test_fields.py
- tests/test_forms.py
- tests/test_multipart.py
- tests/test_views.py
- tox.ini
Also, ensure test uploaded files have unique names.
> Delete uploaded files after test cases conclude

- django-s3-file-field-client/src/client.ts
> Add progress callback to client library

- django-s3-file-field-client/src/client.ts
Reverts girder/django-s3-file-field#134 , based on discussion in that PR.
> Revert "Add progress callback to client library"

- django-s3-file-field-client/src/client.ts
* Add missing parameter descriptions.
* Remove `@returns` types, since they don't add any information.
> Improve the JSDocs for the client library

- README.md
I could have used this documentation when adding S3FF to a project, so I added it.
> Add section to README on form media injection

- setup.py
See https://github.com/girder/django-composed-configuration/pull/96 for rationale.
> Remove zip_safe flag to setup

- DEVELOPMENT.md
- setup.cfg
> Remove config for bumpversion

- s3_file_field/views.py
> Prevent CSRF checks on views, but allow normal authentication to proceed

- javascript-client/package-lock.json
- javascript-client/package.json
- javascript-client/src/client.ts
> Add airbnb lint rules

- s3_file_field/widgets.py
This is no longer inlined into the JS.
> Include the widget's CSS as a form asset

- javascript-client/src/client.ts
It's possible to instantiate a single `S3FileFieldClient`, and then call `uploadFile` repeatedly (including in parallel). In this case, each upload should be reporting its own separate progress.
Accordingly, this moves the optional `onProgress` parameter out of the constructor and into the `uploadFile` method.
> In the JS client, report progress separately for each upload

- s3_file_field/fields.py
- s3_file_field/fixtures.py
This can be merged once:
* https://github.com/typeddjango/django-stubs/pull/731
* https://github.com/typeddjango/django-stubs/pull/732
are released.
> Revert "Work around upstream type checking problems"

- s3_file_field/__init__.py
- setup.py
This was already started in #281.
> Make Django 3.2 the minimum supported version

- tox.ini
See: https://github.com/typeddjango/django-stubs/pull/1724
> Pin django-stubs to work around an upstream bug

- s3_file_field/_registry.py
- tests/test_registry.py
> Make re-registration a warning, not an error

- .github/workflows/ci.yml
- .github/workflows/release.yml
This reverts commit aa2b8effa911dbd90a262ae34212affd2c33153c.
> Revert "Use an older NodeJS version, fixing a build error"

- javascript-client/README.md
@mvandenburgh please note this change
> Update JS client README to reflect the actual API
